[hkg-jgt-ssd]
host_base = http://10.18.1.151:9000
access_key = GDp7R2npyFJvIrO1JbAy
secret_key = rbg02CERwV4o7pdKwYT0auarRa5LZiZslrcl8c06
session_token = 
# path | dns | https://www.%(bucket).example.com
bucket_lookup = path
region = auto
verify_ssl = False
default_mime_type = binary/octet-stream
multipart_chunk_size_mb = 15
